### PR TITLE
Improve player texture quality

### PR DESCRIPTION
**Pull request by Calinou**
This improves player textures by replacing them with versions upscaled using Waifu2x. Textures were then sharpened using GIMP's NL Filter, and the contrast increased using the Levels tool.

I remember seeing an issue mentioning this, but I can't find it right now.

## Preview

*To compare, open images in a new tab by right-clicking them.*

#### Before

before_flamer

#### After

after_flamer

#### Before

before_pistol

#### After

after_pistol

#### Before

before_thirdperson

#### After

after_thirdperson

### CODE REVIEW

**Comment by qreeves** [comment]
Will definitely need to generate the DDS variants before it can be merged. @molexted and I were also discussing increasing the contrast a bit in the diffuse if you want to do that in the process of doing this.

**Comment by Calinou** [comment]
I pushed an update with sharpened textures and increased contrast:

### Flamer

after2_flamer

### Pistol

after2_pistol

### Third person

after2_thirdperson

**Comment by acerspyro** [comment]
@molexted Would you like to present (and maybe add) your modifications to the player model's spec map, as discussed on IRC?

**Comment by Calinou** [comment]
DDS variants added, this pull request is now ready for review.

**Pull request merged**
