### PR TITLE
new rifle animations

### PR DESCRIPTION
**Pull request by cloudziq**
changes:
5 new rifle anims
a little \cleaned\ player.cfg with everything set up as before with only necessary changes

tested 10 times :)

### CODE REVIEW

**Comment by qreeves** [comment]
Does modifying the `iqmpitchcorrect` change anything else though? I'm concerned it'll impact the aim direction.

**Comment by cloudziq** [comment]
from my experience, this ruins anims a little, resulting in overlapping fingers/hands with weapon.  Enabling these lines does not change aim direction too much, or its barely visible - almost unnoticeable. 
I don't know what to do with this, maybe is there a sollution to not alter arms at all, but maybe just a ribs ?

**Comment by qreeves** [comment]
OK, we'll have to play with this in the future. I'll merge this for now.

**Comment by cloudziq** [comment]
yes sir!

**Pull request merged**
